### ISSUE TITLE
[feature] Duplicate a page into another Workspace

### ISSUE THREAD

**Issue by mvgentil** [briefercloud/briefer#104]
It would be a great feature if it were possible to duplicate a page and send it to another workspace.
Why? Imagine I’m working on a project for a customer, using their database connection and credentials.
Now, imagine I have another customer who wants the same analysis/dashboard or something very similar, with only minor changes.
Each customer would have access to their respective workspace as viewers, but as a developer and admin of both workspaces, I would appreciate the ability to duplicate the notebook/dashboard across different workspaces.
Does that make sense? 😊

**Comment by mvgentil** [comment]
I just have seen that the issue #55 could resolve the problem in a certain way.
We could just export the .ypnb file from one workspace and upload it into another workspace.
But the dashboard view still would be missing anyway.

**Comment by vieiralucas** [comment]
Hi @mvgentil

I think that #55 is the way to accomplish this task, I think we would export a `.briefer` file and that should include the dashboards.

I'm not sure how we could implement something better than that for sending documents across workspaces, in the OSS version there is only one Workspace anyway, this is a feature we might have in the cloud version sometime but not a priority atm.

I encourage you to engage in #55, it is not a top priority for our own team inside Briefer but I'll be more than happy to help you or anyone else contribute to Briefer.
