### ISSUE TITLE
[bug] python cell output image is right-aligned

### ISSUE THREAD

**Issue by marquesine** [briefercloud/briefer#105]
When output images (or anything else) are minor than the output box, they should be left aligned.

![image](https://github.com/user-attachments/assets/8b391dd9-35a5-401e-a2cb-71265de566b4)

Removing `items-end` should be sufficient. ⬇️

```html
<div class="flex flex-col items-end">
  <img class="printable-block" alt="generated image" src="data:image/png;base64, ...">
  <button class="...">PNG</button>
</div>
```

**Comment by marquesine** [comment]
Removing `items-end` will make the download button much wider. I think it looks good, but we can adjust the button if needed.

![image](https://github.com/user-attachments/assets/e58fddff-9bc3-4621-be93-499f95c3d4b9)

**Comment by vtfg** [comment]
I'll fix this.

**Comment by vieiralucas** [comment]
@vtfg thank you, I'll assign this to you so that other people don't waste their time.
Let me know if you're not comfortable with the assignment. 

Also, thank you for the issue @marquesine, that's a bug for sure.

**Comment by vtfg** [comment]
@marquesine Can you help me reproduce this issue? I want to check if it has actually been fixed.

A sample Python code that outputs a small PNG would help.
