### ISSUE TITLE
Unable to save the page name and execute any tasks like Run SQL, Python.

### ISSUE THREAD

**Issue by mydalat** [briefercloud/briefer#106]
When I enter the page title and press Enter, the title does not automatically save.

And when running any task within each page, it cannot be executed.

`[I 2024-09-21 05:04:54.533 ServerApp] Current working directory: /home/jupyteruser
[I 2024-09-21 05:04:54.537 ServerApp] Received request to list files in directory: /home/jupyteruser
[I 2024-09-21 05:04:54.537 ServerApp] Returning list of 7 files from directory: /home/jupyteruser
[05:04:58.998] INFO (37): Updated schedules
    created: 0
    updated: 0
    deleted: 0
    unchanged: 0
    module: "schedule"
[05:05:04.000] INFO (37): Updated schedules
    created: 0
    updated: 0
    deleted: 0
    unchanged: 0
    module: "schedule"
[05:05:09.002] INFO (37): Updated schedules
    created: 0
    updated: 0
    deleted: 0
    unchanged: 0
    module: "schedule"
[I 2024-09-21 05:05:12.334 ServerApp] Current working directory: /home/jupyteruser
[I 2024-09-21 05:05:12.337 ServerApp] Received request to list files in directory: /home/jupyteruser
[I 2024-09-21 05:05:12.337 ServerApp] Returning list of 7 files from directory: /home/jupyteruser
[05:05:14.003] INFO (37): Updated schedules`

![Screenshot 2024-09-21 120901](https://github.com/user-attachments/assets/77d0c7dd-76e3-4188-9683-a4c974fcb59c)

**Comment by mydalat** [comment]
I have discovered that if accessed via IP without SSL, it works fine.

However, if the SSL configuration for Nginx is added, you can log in but cannot edit or run tasks.

To run SSL with a custom domain, how should we configure it correctly?

**Comment by vieiralucas** [comment]
Hi @mydalat sorry for the delay here. I think the issue you're facing is probably related to missing some configuration in your `nginx.conf` to allow for websockets connections.
Can you double check if you have these?
```nginx
proxy_request_buffering off;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "Upgrade";
```
You should also consider increasing max body size specially if you plan to use the files feature, the nginx default is quite low.
```nginx
client_max_body_size 0;
```
Setting to 0 disables the max size.

I'll close this for now, feel free to reply here and I'll reopen this issue.

Thank you!
