### ISSUE TITLE
Error installing scikit-learn package

### ISSUE THREAD

**Issue by Matheuszl** [briefercloud/briefer#108]
I'm trying to install pip install scikit-learn and I get the following error: 

Installing collected packages: threadpoolctl, joblib, scikit-learn
ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: '/app/jupyter/venv/lib/python3.11/site-packages/threadpoolctl.py'
Check the permissions.
Note: You may need to restart the kernel to use the updated packages.

When searching for the path '/app/jupyter/venv/lib/python3.11/site-packages/threadpoolctl.py', the file threadpoolctl.py is not in the site-packages directory.

![image](https://github.com/user-attachments/assets/9742189b-23d9-4d4a-bd3d-c078ff571342)

**Comment by vieiralucas** [comment]
Hey @Matheuszl, thank you for this issue.
Can you share which version of Briefer you're running? I think we fixed this problem on #85
