### ISSUE TITLE
move comments to websockets

### ISSUE THREAD

**Issue by vieiralucas** [briefercloud/briefer#111]
current implementation just keeps listing comments every 5 seconds which is pretty annoying

https://github.com/briefercloud/briefer/blob/a341ecd326aad95dd2caf75e6372d79719b8347e/apps/web/src/hooks/useComments.ts#L26

**Comment by hiteshwadhwani** [comment]
I would like to work on it.

**Comment by hiteshwadhwani** [comment]
Should we create a new ws connection for comments or use the workspace ws connection?

**Comment by hiteshwadhwani** [comment]
@vieiralucas

**Comment by vieiralucas** [comment]
Hi @hiteshwadhwani thank you for working on this issue.
We should use the same websocket connection.
I’ll assign this issue to you.

**Comment by vieiralucas** [comment]
This commit can used as reference for how to implement this
80a83ee1828764ff4548c01a92d5cd2b79f9bf55
