### ISSUE TITLE
Allow typing into select inputs to find options

### ISSUE THREAD

**Issue by lucasfcosta** [briefercloud/briefer#122]
We need to turn the "select" input into kind of a combobox that allows choosing a single option - that way people can type in to find what they want instead of going through all the options.

**Comment by hiteshwadhwani** [comment]
@lucasfcosta I would like to work on it

**Comment by hiteshwadhwani** [comment]
@lucasfcosta , should we consider replacing all select fields with comboboxes? In my view, a combobox is most effective when dealing with larger lists, as it provides better usability in such cases.

**Comment by lucasfcosta** [comment]
hey @hiteshwadhwani! I saw you currently already have a PR open and @joezein-oss offered to work on this right now via DMs so I'll assign it to him for now

Still, I'd love it if you want to tackle this one: https://github.com/briefercloud/briefer/issues/72

It's high priority and we haven't got a PR for it yet

**Comment by joezein-oss** [comment]
can you please assign this to me 🙏

**Comment by hiteshwadhwani** [comment]
Sure @lucasfcosta

**Comment by hiteshwadhwani** [comment]
@lucasfcosta Since I’m working on a Mac, I won’t be able to work on this issue #72

**Comment by vieiralucas** [comment]
Hi @joezein-oss, just the `DropdownInputBlock`
![image](https://github.com/user-attachments/assets/76163840-828e-4dd8-accc-03ea4298730b)
