### ISSUE TITLE
visualization crashes when column is of type date (NOT DATETIME)

### ISSUE THREAD

**Issue by vieiralucas** [briefercloud/briefer#15]
Right now you can't create a visualization with a field of type date (notice, I'm not talking about the `datetime` type, I'm talking about the `DATE` type).

You'll get bonus points if you find a way of making `vis.to_json` never fail because of JSON not being serializable - which is the root cause of this issue.

**Comment by Jai0401** [comment]
Could someone please assign this issue to me? I'd like to work on fixing it.

**Comment by adityarawat007** [comment]
Hey @lucasfcosta can you please assign me this task, i would like to work on it .

**Comment by vieiralucas** [comment]
@Jai0401 sure, thank you. Feel free to ask questions if you need help.

**Comment by vieiralucas** [comment]
Failed to reproduce this, I'll close for now.
