### ISSUE TITLE
Unable to create checkboxes using markdown syntax

### ISSUE THREAD

**Issue by offpepe** [briefercloud/briefer#16]
In some cases where a had to declare structures like to-do lists, when trying to create check-boxes using markdown syntax:
```txt
- [ ]
``` 
does not works. 
Can i create check-boxes in some other way?

**Comment by joezein** [comment]
can I get this one assigned to me?

**Comment by vieiralucas** [comment]
Hi @joezein, I missed your message, I'm sorry. Do you still want to work on this one?
If so, let me know and I'll assign to you.

This should be implemented by integrating the [Task List](https://tiptap.dev/docs/editor/extensions/nodes/task-list) Tiptap extension.

**Comment by joezein-oss** [comment]
I can take it yes
