### ISSUE TITLE
export to png

### ISSUE THREAD

**Issue by lvgalvao** [briefercloud/briefer#18]
i need to export to png in open source version
thanks

**Comment by kaiohp** [comment]
Up!

**Comment by ArgusPortal** [comment]
UP

**Comment by KiitoNahari** [comment]
Up!

**Comment by ViniciusCODER** [comment]
up!

**Comment by jobsonbarbosa** [comment]
up!

**Comment by Adrianogvs** [comment]
up!

**Comment by deydsonx** [comment]
Up ,

**Comment by Jonathanac27** [comment]
up!!

**Comment by flpbrcco** [comment]
up!!

**Comment by flpbrcco** [comment]
up!!

**Comment by jwalmir** [comment]
Up

**Comment by lauroPereira** [comment]
up

**Comment by vtfg** [comment]
I would like to work on it.

**Comment by lucasfcosta** [comment]
Hey @vtfg, thanks so much for offering to contribute to Briefer!

Here are some quick guidelines for implementing it visually:

![guidelinespng](https://github.com/user-attachments/assets/fb5d231e-101e-4074-968f-87c59375c4f4)

A few more details:

* This button should only appear in the notebook view - it should not appear in the dashboard
* It should export the graph without the filters on the left (the ones you can hide/show clicking the small arrow on the left)

**Comment by nkalpakis21** [comment]
i see this has been open for awhile. is there trouble getting a dev to fix this issue? what is blocking this for so long

**Comment by vtfg** [comment]
I had some trouble to setup this project for local development. I will be working on this today.

**Comment by lucasfcosta** [comment]
@nkalpakis21 thanks for the ping here, @vtfg is working on this! We're almost done, just one minor detail before we can merge it!

**Comment by lucasfcosta** [comment]
Hey everyone! This will be available on release `v0.0.15`. Thank you @vtfg for working on this!
