### ISSUE TITLE
Connect to Microsoft SQL

### ISSUE THREAD

**Issue by sanipnb** [briefercloud/briefer#19]
I have Microsoft SQL Server but don't know how to connect to it

**Comment by lucasfcosta** [comment]
Hey @sanipnb, thanks for this issue! We should definitely implement this.

I would love some help supporting SQL Server - if anyone wants to tackle this issue please leave a comment and I can point you in the right direction.

**Comment by sanipnb** [comment]
Hi @lucasfcosta I'm interested to tackle this issue
