### ISSUE TITLE
Connect python notebook to MongoDB

### ISSUE THREAD

**Issue by MatheusValera** [briefercloud/briefer#21]
I opened a PR to add the MongoDB connection package to the dependencies, not being a data source, but being able to minimally connect to another database from Python for those who are aware of the queries.

**Comment by MatheusValera** [comment]
https://github.com/briefercloud/briefer/pull/17

**Comment by MatheusValera** [comment]
And also configure package management permission between the application within docker with venv. Currently, Jupyter Notebook does not have permission to add packages, changing this would also resolve the pull request above.
![image](https://github.com/user-attachments/assets/acebb4cb-cc15-4ad9-83fa-971fcf0811e3)

**Comment by lucasfcosta** [comment]
Hey @MatheusValera, just saw your comment on #25! Thanks for this pull request. I'll have a look at your pull-request.

I think we eventually should have a native connector for MongoDB, but I think right now what you proposed is a good compromise.

**Comment by MatheusValera** [comment]
Thank you very much @lucasfcosta. I believe that the code is already a lot of use.
