### ISSUE TITLE
Pip install is not working in the open-source version

### ISSUE THREAD

**Issue by lucasfcosta** [briefercloud/briefer#25]
We still need to add more details to this, but `!pip install lib` doesn't seem to be working in the open-source version.

![pyinstall](https://github.com/user-attachments/assets/960daef0-20f5-4cda-9a8c-c9441a45b507)

**Comment by MatheusValera** [comment]
Same note I put in this issue: https://github.com/briefercloud/briefer/issues/21

**Comment by d8rt8v** [comment]
As a workaround for now, you can exec into docker container and do 

```
source venv/bin/activate

pip install your-stuff

```

**Comment by vieiralucas** [comment]
If you're reading this issue today, this should be fixed since v0.0.17
