### ISSUE TITLE
Error when initializing

### ISSUE THREAD

**Issue by henriquehashimoto** [briefercloud/briefer#257]
I'm trying to use Briefer locally, but I keep receiving an error when I try to start.

Installed with `pip install briefer`

When I do the command "`briefer`", I receive the following error:

![image](https://github.com/user-attachments/assets/8fe415da-8a50-451f-96b5-65a957515fd4)

How can I solve this?

**Comment by lucasfcosta** [comment]
Hey @henriquehashimoto! Thanks for opening this issue!

Initially, this looks like a problem with docker not being up. Can you ensure that you have docker up and running on your machine when starting Briefer?

If you already have docker and it's running, can you also try running it as a container and see if that works?

```
# Run Briefer using Docker
docker run -d \
  -p 3000:3000 \
  -v briefer_psql_data:/var/lib/postgresql/data \
  -v briefer_jupyter_data:/home/jupyteruser \
  -v briefer_briefer_data:/home/briefer \
  briefercloud/briefer
```
