### ISSUE TITLE
Ability to turn a file directly into a dataframe without having to go through the files panel first

### ISSUE THREAD

**Issue by lucasfcosta** [briefercloud/briefer#36]
It should be possible to drag a file straight into a Python block to upload it and turn it into a dataframe without going through the files tab.

Same for SQL and DuckDB. SQL should switch into DuckDB and select * from file.

**Comment by vieiralucas** [comment]
I think we can drop this one for now, it is not hard to upload a File to the Files side bar and click "use in query".
