### ISSUE TITLE
Better troubleshooting documentation for docker

### ISSUE THREAD

**Issue by KiitoNahari** [briefercloud/briefer#45]
On deb based linux there's two ways to install docker, via apt or deb package to install Docker Desktop application, if running Deb package the Unix service doens necessary run. But docker works perfectly, but the briefer api doens locate it.
idk if am i doing something wrong but followed step by step correctly and doesnt work. when i mount the image manually by docker run -d -p 8080:8080 it works one time, but when the container stops, and run again sometimes doenst work, and sometimes the sql cant find the paths. 
Im solving it by reinstalling docker via apt and conect to the desktop docker manualy, but for beginners lnx users it may be a bigger issue...
![Captura de tela de 2024-09-13 14-57-32](https://github.com/user-attachments/assets/248f172a-9865-4f4b-adc0-c5e62701d4f4)
![Captura de tela de 2024-09-13 14-58-42](https://github.com/user-attachments/assets/6b1da0b8-5029-4d80-b7e1-a1e965698637)

**Comment by lucasfcosta** [comment]
Hey Kiito! Thanks for this issue.

I think the right thing to do here is to provide better error messages, but for now, I'd like to suggest that we add a Troubleshooting section in the `README` using `<details>` and mention a few common errors like this one.

In fact I think it would be useful to add that to `DEPLOYMENT.md` too.

What do you think? I'd love to give you feedback on docs if you want to tackle this.

I renamed this issue accordingly.

**Comment by vieiralucas** [comment]
@lucasfcosta we now have a troubleshooting section, do you think this issue can be closed?
Is there something specific to this issue that we should add to the troubleshooting section?

**Comment by lucasfcosta** [comment]
I think we can close this.
