### ISSUE TITLE
delete file has no loading indicator

### ISSUE THREAD

**Issue by lucasfcosta** [briefercloud/briefer#62]
When you delete a file in the file upload panel, it has no loading indicator. It just takes a bit of time before the delete operation finishes and then the file disappears.

We need a better loading indication here.

**Comment by Samuel-Brito19** [comment]
Hi! Can you provide more information about this issue please?

**Comment by vieiralucas** [comment]
Hi @Samuel-Brito19 sure, thank you in advance!

**Comment by vieiralucas** [comment]
Hi @Samuel-Brito19, 

Sure, I'll improve the description soon.
