### ISSUE TITLE
Adding user shows no loading indicator nor disables button

### ISSUE THREAD

**Issue by lucasfcosta** [briefercloud/briefer#63]

**Comment by Samuel-Brito19** [comment]
Hi! Can you provide more information about the issue please? I would like to contribute with this project!

**Comment by lucasfcosta** [comment]
Hey @Samuel-Brito19, we ended up assigning this to @vieiralucas because this is very high priority for us. Apologies that it's not available.

How about you take this one? https://github.com/briefercloud/briefer/issues/70

That's a great one to get started - it already includes detail and is a pretty important part of Briefer's UX.

**Comment by Samuel-Brito19** [comment]
Oh right, let's do it!
