### ISSUE TITLE
show "loading" indication when pinging a new data source

### ISSUE THREAD

**Issue by lucasfcosta** [briefercloud/briefer#70]
When creating a new data source, pinging it can take a while. We need an intermediary state saying "Connecting" or something similar while pinging.

This is probably an easy front-end-only change.

**Comment by Samuel-Brito19** [comment]
I did a PR for this issue!

**Comment by vieiralucas** [comment]
Samuel has told me that he'll not have time to work on this anymore. This is open again for anyone who might be interested in fixing this bug.

Thank you @Samuel-Brito19

**Comment by joezein-oss** [comment]
I can take that one
