### ISSUE TITLE
Integration - SQL Server/Microsoft SQL Server

### ISSUE THREAD

**Issue by leonardoasfernandes** [briefercloud/briefer#81]
Add an integration connection to the SQL Server from Microsoft to the list of DB connections.

**Comment by lucasfcosta** [comment]
I'd love this to be implemented! Anyone interested in adding a SQL Server connector would have my full support to implement it!

**Comment by joezein-oss** [comment]
has this been merged? can take it if not

**Comment by vieiralucas** [comment]
Closed by #135
