### ISSUE TITLE
Hotkey to focus on pages searchbar would be very useful

### ISSUE THREAD

**Issue by obratim** [briefercloud/briefer#91]
There are some hotkeys already, and they helps a lot.

Adding a hotkey to focus on pages searchbar would be great, righ now it is only possible to mouse click on the search icon or mouse click on the page itself to open that page. Hotkey would be very useful.

Also, hotkeys for other page manipulation like adding new page or removing selected page would be helpful.

**Comment by vieiralucas** [comment]
Hello @obratim, You should be able to open the searchbar by pressing `CMD + k`
Is that not working for you?

**Comment by vieiralucas** [comment]
I'll go ahead and close this one. @obratim, let me know if my answer above does not solve your issue.

**Comment by obratim** [comment]
i meant the notebook that are listed on the right side, there is label "Pages" above this list.
Ctrl+K allows to search through brouser pages, but how to navigate through notebooks?

couldn't answer earlear, sorry

![image](https://github.com/user-attachments/assets/60c6a220-5969-49d4-9580-2d41ef060a08)
