### ISSUE TITLE
CMD+A (select all text) freezes editor

### ISSUE THREAD

**Issue by lucasfcosta** [briefercloud/briefer#96]

**Comment by marquesine** [comment]
Using Chrome Developer Tools, under the Performance tab, I observed that every character typed or action performed took approximately 2-3 seconds to resolve. This makes the editor difficult to use effectively.

The issue can be reproduced by using the Chrome browser and monitoring the Performance tab. Based on my observations, I suspect this may be related to the autosuggestion functionality or a similar feature.

**Comment by marquesine** [comment]
Hello,

I was able to reproduce the performance issue I reported earlier.

The problem usually occurs after running a notebook in edit mode for a few minutes. As demonstrated in the attached image, there is a noticeable delay when typing. For example, when I type a key (such as a closing parenthesis), it takes approximately one second (~1000 ms) for the character to appear in the editor.

![image](https://github.com/user-attachments/assets/0d446984-8f6d-452d-81e4-b3688213a36f)

Here is the [JavaScript CDN file](https://cdn.jsdelivr.net/npm/monaco-editor@0.43.0/min/vs/editor/editor.main.js) where the browser violations are pointing.

Please let me know if you need further information.

**Comment by vieiralucas** [comment]
Hi @marquesine, I think I solve this with #103

**Comment by marquesine** [comment]
Hey @vieiralucas,

Thanks for your attention to this!

While selecting all the text (Cmd + A) in the editor feels smooth now, typing in the Python editor still becomes laggy after a few minutes with Briefer open in the browser.

![image](https://github.com/user-attachments/assets/ea85cd23-3e48-4c7b-8504-d7459b159577)

By 'keydown', the console logs mean any key press—whether typing a character or moving through the text using the arrow keys.

Here’s the JavaScript file with the violation warnings (see line 852): 

```javascript
// [event.ts]
// ...

class Stacktrace {

	static create() {
		return new Stacktrace(new Error().stack ?? '');
	}

	private constructor(readonly value: string) { }

	print() {
		console.warn(this.value.split('\n').slice(2).join('\n'));  // line 852
	}
}
class UniqueContainer<T> {
	stack?: Stacktrace;
	constructor(public readonly value: T) { }
}
const compactionThreshold = 2;

type ListenerContainer<T> = UniqueContainer<(data: T) => void>;
type ListenerOrListeners<T> = (ListenerContainer<T> | undefined)[] | ListenerContainer<T>;
```

**Comment by vieiralucas** [comment]
Hi @marquesine,

Do you think you can create a small document, that you can share where this happens?
I'm having a hard time reproducing this specific problem and getting this "Violation" warnings on my side. Do I have to enable something in my browser?

Really appreciate your detailed bug reports, thanks for all this debugging ❤️
