### ISSUE TITLE
 table `public.Workspace` does not exist in the current database.

### ISSUE THREAD

**Issue by lpxiangyan9** [briefercloud/briefer#98]
after  run ./start-dev.sh and yarn install && yarn dev
throw   err: {
@briefer/api:dev:       "type": "PrismaClientKnownRequestError",
@briefer/api:dev:       "message": "\nInvalid `prisma.workspace.findMany()` invocation:\n\n\nThe table `public.Workspace` does not exist in the current database.",
@briefer/api:dev:       "stack":
@briefer/api:dev:           PrismaClientKnownRequestError: 
@briefer/api:dev:           Invalid `prisma.workspace.findMany()` invocation:
@briefer/api:dev:           
@briefer/api:dev:           
@briefer/api:dev:           The table `public.Workspace` does not exist in the current database.
@briefer/api:dev:               at Ln.handleRequestError (/Users/liupeng/workspaces/lp/briefer/node_modules/@prisma/client/runtime/library.js:121:7753)
@briefer/api:dev:               at Ln.handleAndLogRequestError (/Users/liupeng/workspaces/lp/briefer/node_modules/@prisma/client/runtime/library.js:121:7061)
@briefer/api:dev:               at Ln.request (/Users/liupeng/workspaces/lp/briefer/node_modules/@prisma/client/runtime/library.js:121:6745)
@briefer/api:dev:               at async l (/Users/liupeng/workspaces/lp/briefer/node_modules/@prisma/client/runtime/library.js:130:9633)
@briefer/api:dev:       "name": "PrismaClientKnownRequestError",
@briefer/api:dev:       "code": "P2021",
@briefer/api:dev:       "clientVersion": "5.19.0",
@briefer/api:dev:       "meta": {
@briefer/api:dev:         "modelName": "Workspace",
@briefer/api:dev:         "table": "public.Workspace"
@briefer/api:dev:       }
@briefer/api:dev:     }

find the postgre  has database briefer but not exists table  Workspace  
can't find  Workspace   in  the  data/psql/ecommerce/schema.sql

**Comment by lucasfcosta** [comment]
Hey @lpxiangyan9! This usually happens if you haven't run migrations.

Please run them from the `database` package:

```
cd packages/database
POSTGRES_PRISMA_URL="postgres://postgres:password@localhost:5432/briefer" npx prisma migrate dev
```

I'll close this for now, but we can reopen if you're still having issues after running migrations.
