### ISSUE TITLE
Unable to log in

### ISSUE THREAD

**Issue by fujl** [briefercloud/briefer#99]
![image](https://github.com/user-attachments/assets/c19f38cd-21cc-4a60-a4cf-b262e36f36d2)
http://10.170.22.62:3000/api/v1/workspaces
Request Method:
GET
401 Unauthorized

**Comment by 42795748** [comment]
I log in with the account and passwd I just set up and nothing happened but a simple refresh of the login page

**Comment by fujl** [comment]
> I log in with the account and passwd I just set up and nothing happened but a simple refresh of the login page

That's the phenomenon

**Comment by Grasiella** [comment]
same

**Comment by vieiralucas** [comment]
Hello everyone, you probably need to set “ALLOW_HTTP=true”
When not running on local host brifer  only works in https by default

**Comment by fujl** [comment]
set ALLOW_HTTP=true，The problem has been resolved.

**Comment by vieiralucas** [comment]
Thank you @fujl, I'm glad it worked!
